---

- hosts: all
  become: true
  tasks:

# for arch
  - name: install apache2 package
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
        - "{{ firewall_package }}"
      state : latest
      update_cache: yes # preferred to be kept in seperate play
