---


# updating all packages on all the hosts/servers
- hosts: all
  become: true
  pre_tasks:               # these pre_tasks will be executed before tasks

  - name: install updates (mint)
    tags: always
    apt:
      upgrade: dist 
      update_cache: yes
    when: ansible_distribution == "Linux Mint"

  - name: install updates (arch)
    tags: always
    pacman:
      update_cache: yes
    when: ansible_distribution == "Archlinux"

- hosts: workstations
  become: true
  tasks:
  - name: install unzip
    package:
      name: unzip

# terraform will be installed on workstations ie. your system
  - name: install terraform
    unarchive:
        src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

# installing apache and php on web_servers group hosts/servers 
- hosts: web_servers
  become: true
  tasks: 

  - name: install apache and php for mint servers
    tags: apache,apache2,mint
    apt:
      name:
        - apache2
        - php
        - firewalld
      state: latest
    when: ansible_distribution == "Linux Mint"

  - name: install apache and php for arch servers 
    tags: apache,arch
    pacman:
      name:
        - apache
        - php
        - firewalld
      state: latest
    when: ansible_distribution == "Archlinux"

  # starting and enableling the apache service
  - name: start apache (in mint)
    tags: apache2,apache,mint
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Linux Mint"

  # making changes to the apache configuration file
  - name: change KeepAliveTimout configuration variable
    tags: apache,apache2,mint
    lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: '^KeepAliveTimeout'
      line: KeepAliveTimeout 10
    when: ansible_distribution == "Linux Mint"
    register: apacheState    # this is a variable which stores the state of the service

  # restarting the apache service
  - name: restart apache service
    tags: apache,apache2,mint
    service:
      name: apache2
      state: restarted
    when: apacheState.changed   # checking if the apacheState is changed or not

  - name: copy default html file for site
    tags: apache,apache2
    copy:
      src: index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package on mint servers
    tags: mint,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Linux Mint"

  - name: install mariadb package on arch
    tags: db,arch,mariadb
    pacman:
      name: mariadb
      state: latest
    when: ansible_distribution == "Archlinux"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba   # the name of the package is same across pacman and apt
      state: latest

