- name: install apache and php for mint servers
  tags: apache,apache2
  package:
    name:
      - "{{ apache_package_name }}" 
      - "{{ php_package_name }}"
      - "{{ firewalld_package_name }}"
    state: latest

# starting and enableling the apache service
- name: start and enabling apahe
  tags: apache2,apache
  service:
    name: "{{ apache_service }}" 
    state: started
    enabled: yes

  # making changes to the apache configuration file
- name: change KeepAliveTimout configuration variable
  tags: apache,apache2,mint
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^KeepAliveTimeout'
    line: KeepAliveTimeout 4 
  when: ansible_distribution == "Linux Mint"
  notify: restart_apache
#  register: apacheState    # this is a variable which stores the state of the service

# restarting the apache service
#- name: restart apache service
#  tags: apache,apache2
#  service:
#    name: "{{ apache_service }}" 
#    state: restarted
#  when: apacheState.changed   # checking if the apacheState is changed or not

- name: copy default html file for site
  tags: apache,apache2
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
