- name: add ssh key for wigiwee
  tags: always
  authorized_key:
    user: wigiwee
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCMVpM8iQrpAnZwJSxKNB8uyDEsldYyLnSHeEHg7TvBPUrddY9NmSgCVYjn0bI6qZ23/VIq8g9kQq1gRN6fe1asbrw/wvWWWqJYWme9fMdvAJ0GdL2LouBMF6dbBBgI6/U0iC7LMUblfcBRKY+HpH1kZQbiPwKst2S5XsP6pNSxwViJBOQ/7SrSrnhik2+YcPD9Vb5E7wbCB3Letq0Uw/mQDgV1sR6d/9jDHD6o4hW9mr9lIVFHgZCOiWMVrpfddPljoW60bS5SGTsY+PXn8/8PSE2Vr3xNsS6SHnrCfaKmo0hBOG8XZCvbOHOWcf6TF0nMhe39wEXaZp0oK0uIdBsfbkilKl/fuDMqKm3qBEHO7FKRxD4uHfslqQ0/eAVX9swP63X3eF8A+gEipvxsdcl14T3nk/4nAHyfOys1hse57W38lhTiph82vni/tHW90Y+nA8/Ru6HeQKx4BgFj+2oGJSPo5tjX8mLgHKkqJUv/LdeD9LiLfXOm91B7aK02GAk= happypotter@archlinux"
